// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/comments/:imageId": {
    params: {
      "imageId": string;
    };
  };
  "/api/comments": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/comments/:imageId" | "/api/comments";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.comments.ts": {
    id: "routes/api.comments";
    page: "/api/comments/:imageId";
  };
  "routes/api.comments-create.ts": {
    id: "routes/api.comments-create";
    page: "/api/comments";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/api.comments": typeof import("./app/routes/api.comments.ts");
  "routes/api.comments-create": typeof import("./app/routes/api.comments-create.ts");
};