// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/vouchers": {
    params: {};
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/vouchers" | "/terms";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/vouchers.tsx": {
    id: "routes/vouchers";
    page: "/vouchers";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
};