import type { LiveFlight } from './flightradar.server'

// ============================================================================================================
// Deterministic mock data for local development
// ============================================================================================================

export function generateMockFlights(): LiveFlight[] {
    return [
        {
            icao24: '4B1613',
            callsign: 'SWR123',
            latitude: 50.64,
            longitude: 5.58,
            heading: 270,
            altitude: 36000,
            speed: 480,
            squawk: '1000',
            aircraft: 'A320',
            registration: 'HB-JDA',
            origin: 'ZRH',
            destination: 'LHR',
            airline: 'SWR',
            onGround: false,
            verticalSpeed: 0,
        },
        {
            icao24: '3C6745',
            callsign: 'DLH456',
            latitude: 50.60,
            longitude: 5.50,
            heading: 90,
            altitude: 28000,
            speed: 420,
            squawk: '2345',
            aircraft: 'B738',
            registration: 'D-ABCI',
            origin: 'FRA',
            destination: 'BRU',
            airline: 'DLH',
            onGround: false,
            verticalSpeed: -500,
        },
        {
            icao24: '440123',
            callsign: 'RYR789',
            latitude: 50.70,
            longitude: 5.65,
            heading: 180,
            altitude: 22000,
            speed: 390,
            squawk: '7412',
            aircraft: 'B738',
            registration: 'EI-DCL',
            origin: 'STN',
            destination: 'CRL',
            airline: 'RYR',
            onGround: false,
            verticalSpeed: -1200,
        },
        {
            icao24: '4CA123',
            callsign: 'EIN101',
            latitude: 50.55,
            longitude: 5.45,
            heading: 315,
            altitude: 40000,
            speed: 510,
            squawk: '5531',
            aircraft: 'A333',
            registration: 'EI-FNG',
            origin: 'DUB',
            destination: 'CDG',
            airline: 'EIN',
            onGround: false,
            verticalSpeed: 0,
        },
        {
            icao24: '3944E5',
            callsign: 'AFR221',
            latitude: 50.63,
            longitude: 5.57,
            heading: 45,
            altitude: 0,
            speed: 0,
            squawk: '2000',
            aircraft: 'E190',
            registration: 'F-HBLF',
            origin: 'LGG',
            destination: 'MRS',
            airline: 'AFR',
            onGround: true,
            verticalSpeed: 0,
        },
    ]
}
