apiVersion: apps/v1
kind: Deployment
metadata:
    name: monorepo-backend
spec:
    template:
        spec:
            containers:
                - name: backend
                  env:
                      - name: NAMESPACE_ENV
                        value: production

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: monorepo-frontend
spec:
    template:
        spec:
            containers:
                - name: frontend
                  env:
                      - name: NAMESPACE_ENV
                        value: production

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: monorepo-config
data:
    NAMESPACE_ENV: 'production'
